type TeamsAttendee = {
  email: string
  name?: string | null
}

type CreateTeamsMeetingInput = {
  title: string
  startAt: string
  endAt: string
  participants?: unknown[]
  organizerUpn?: string
}

type GraphTokenCache = {
  accessToken: string
  expiresAtMs: number
} | null

let tokenCache: GraphTokenCache = null

function getRequiredEnv(name: string): string {
  const value = process.env[name]?.trim()
  if (!value) {
    throw new Error(`Missing environment variable: ${name}`)
  }
  return value
}

function getOrganizerUpn(override?: string): string {
  return (
    override?.trim() ||
    process.env.MICROSOFT_TEAMS_ORGANIZER_UPN?.trim() ||
    'academick12@mindx.com.vn'
  )
}

function toGraphDateTime(vnWallClock: string): string {
  const normalized = vnWallClock.trim().replace(' ', 'T')
  const withTz = normalized.endsWith('Z') || /[+-]\d\d:\d\d$/.test(normalized)
    ? normalized
    : `${normalized}+07:00`
  const parsed = new Date(withTz)
  if (Number.isNaN(parsed.getTime())) {
    throw new Error(`Invalid datetime for Teams meeting: ${vnWallClock}`)
  }
  return parsed.toISOString()
}

function extractAttendees(participants: unknown[] | undefined): TeamsAttendee[] {
  if (!Array.isArray(participants)) return []

  const seen = new Set<string>()
  const attendees: TeamsAttendee[] = []

  for (const item of participants) {
    if (!item || typeof item !== 'object') continue
    const row = item as Record<string, unknown>

    const candidateEmail =
      (typeof row.email === 'string' && row.email) ||
      (typeof row.teacher_email === 'string' && row.teacher_email) ||
      (typeof row.user_email === 'string' && row.user_email) ||
      ''

    const email = candidateEmail.trim().toLowerCase()
    if (!email || !email.includes('@')) continue
    if (seen.has(email)) continue

    seen.add(email)
    attendees.push({
      email,
      name:
        (typeof row.name === 'string' && row.name) ||
        (typeof row.teacher_name === 'string' && row.teacher_name) ||
        (typeof row.display_name === 'string' && row.display_name) ||
        null,
    })
  }

  return attendees
}

async function getGraphAccessToken(): Promise<string> {
  const now = Date.now()
  if (tokenCache && tokenCache.expiresAtMs > now + 60_000) {
    return tokenCache.accessToken
  }

  const tenantId = getRequiredEnv('MICROSOFT_TENANT_ID')
  const clientId = getRequiredEnv('MICROSOFT_CLIENT_ID')
  const clientSecret = getRequiredEnv('MICROSOFT_CLIENT_SECRET')

  const tokenUrl = `https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/token`

  const body = new URLSearchParams({
    grant_type: 'client_credentials',
    client_id: clientId,
    client_secret: clientSecret,
    scope: 'https://graph.microsoft.com/.default',
  })

  const response = await fetch(tokenUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: body.toString(),
  })

  const data = await response.json()
  if (!response.ok) {
    throw new Error(
      `Failed to get Microsoft Graph token: ${data?.error_description || data?.error || response.statusText}`,
    )
  }

  const accessToken = String(data.access_token || '')
  const expiresIn = Number(data.expires_in || 3600)
  if (!accessToken) {
    throw new Error('Microsoft Graph token response missing access_token')
  }

  tokenCache = {
    accessToken,
    expiresAtMs: now + Math.max(60, expiresIn - 60) * 1000,
  }

  return accessToken
}

export async function createTeamsMeetingViaGraph(input: CreateTeamsMeetingInput) {
  const token = await getGraphAccessToken()
  const organizerUpn = getOrganizerUpn(input.organizerUpn)
  const attendees = extractAttendees(input.participants)

  const payload = {
    subject: input.title,
    start: {
      dateTime: toGraphDateTime(input.startAt),
      timeZone: 'UTC',
    },
    end: {
      dateTime: toGraphDateTime(input.endAt),
      timeZone: 'UTC',
    },
    isOnlineMeeting: true,
    onlineMeetingProvider: 'teamsForBusiness',
    attendees: attendees.map((a) => ({
      emailAddress: {
        address: a.email,
        name: a.name || a.email,
      },
      type: 'required',
    })),
    body: {
      contentType: 'HTML',
      content: 'Auto-generated by MindX Event Schedule',
    },
  }

  const response = await fetch(
    `https://graph.microsoft.com/v1.0/users/${encodeURIComponent(organizerUpn)}/events`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    },
  )

  const data = await response.json()
  if (!response.ok) {
    throw new Error(
      `Failed to create Teams meeting: ${data?.error?.message || response.statusText}`,
    )
  }

  const meetingUrl =
    data?.onlineMeeting?.joinUrl ||
    data?.onlineMeetingUrl ||
    null

  if (!meetingUrl) {
    throw new Error('Teams meeting created but join URL is missing')
  }

  return {
    meetingUrl: String(meetingUrl),
    meetingId: String(data?.onlineMeeting?.id || data?.id || ''),
    organizerUpn,
    graphEventId: String(data?.id || ''),
    raw: data,
  }
}
